"""
analysis
===========

- Assisting with the analysis and validation of IMP models, including:
  - Plotting score trajectories and checking for equilibration
  - Extracting good scoring models
  - Extracting coordinates (XYZ) and radii (R) of beads from the models
  - Assessing sampling exhaustiveness using sampcon
  - Assessing the sampling and model precision
  - Aligning rigid body pdbs to cluster center model
  - Contact map analysis

<hr>

### Use cases:

#### 1. Perform score-based clustering of models from multiple IMP runs

```bash

python run_analysis_trajectories.py \\
  --modeling_dir /path/to/modeling_dir \\
  --analysis_dir /path/to/analysis_dir \\
  --traj_dir_prefix run_ \\
  --run_start 1 \\
  --run_end 10 \\
  --run_interval 1 \\
  --nproc 4 \\
  --burn_in_fraction 0.1 \\
  --nskip 1 \\
  --restraint_handles "GaussianEMRestraint:EM" "SingleAxisMinGaussianRestraint:SAMGR" \\
  --hdbscan_restraint_handles "EV_sum""EM_sum" \\
  --min_cluster_size 150 \\
  --min_samples 5

```

- `--modeling_dir` argument should point to the directory containing the IMP modeling runs.
- `--analysis_dir` argument should point to the directory where the analysis results will be
  saved.
- `--traj_dir_prefix` argument specifies the prefix of the trajectory directories (e.g.,
  `run_` for directories like `run_1`, `run_2`, etc)
- `--run_start`, `--run_end`, and `--run_interval` arguments specify the range of runs to analyze.
- `--nproc` argument specifies the number of processors to use for parallel processing.
- `--burn_in_fraction` argument specifies the fraction of the trajectory to discard as burn-in.
- `--nskip` argument specifies the number of consecutive frames to skip.
- `--restraint_handles` argument specifies the list of restraint handles to analyze.
  You can specify multiple restraint handles by separating them with spaces. They are
  provided as `handle:short_name` pairs, where `handle` is the name of the restraint and
  `short_name` is a short identifier for the restraint. For example, "GaussianEMRestraint:EM"
  specifies the GaussianEMRestraint with the short name "EM".
- `--hdbscan_restraint_handles` argument specifies the list of restraint handles to use for
  HDBSCAN clustering. These are specified as `f"{short_name}_sum"` for each restraint handle,
  where `short_name` is the short identifier for the restraint.
- `--min_cluster_size` argument specifies the minimum cluster size for HDBSCAN.
- `--min_samples` argument specifies the minimum number of samples for HDBSCAN.

#### 2. Select good scoring models from the a cluster of models

```bash

python variable_filter.py \\
  --cluster_num 1 \\
  --lowest_cutoff -2.0 \\
  --highest_cutoff 2.0 \\
  --step_size 0.01 \\
  --num_models 30000 \\
  --gsmsel /path/to/pmi_analysis_output \\
  --output_dir /path/to/variable_filter_outdir \\
  --restraint_handles "EV_sum" "EM_sum"

```

- `--cluster_num` argument specifies the cluster number to analyze. We usually
  analyze the major cluster. You can use `return_major_cluster` to get the major
  cluster number.
- `--lowest_cutoff` argument specifies the standard deviation multiplier for the most
  stringent cutoff. For example, a value of -2.0 means that models with scores
  below 2 standard deviations from the mean will be selected.
- `--highest_cutoff` argument specifies the standard deviation multiplier for the most
  lenient cutoff. For example, a value of 2.0 means that models with scores above
  2 standard deviations from the mean will be selected.
- `--step_size` argument specifies the increment between successive cutoff values.
- `--num_models` argument specifies the maximum number of models to be selected. The
  total number of selected models (nA + nB) should be less than this value.
- `--gsmsel` argument specifies the path to the directory containing the selected
  models CSV files. These files are generated by the `run_analysis_trajectories.py
  script and contain the scores of the models in each cluster.
- `--output_dir` argument specifies the path to save the output files.

#### 3. Extract the selected good scoring models from modeling runs

```bash

python run_extract_models.py \\
  --modeling_dir /path/to/modeling_dir \\
  --analysis_dir /path/to/analysis_dir \\
  --traj_dir_prefix run_ \\
  --run_start 1 \\
  --run_end 10 \\
  --run_interval 1 \\
  --nproc 4 \\
  --burn_in_fraction 0.1 \\
  --nskip 1 \\
  --cluster_id 1 \\
  --filter_applied \\
  --variable_filter_output_dir /path/to/variable_filter_outdir

```

- `--cluster_id` argument specifies the cluster number to extract models from. We usually
  extract models from the major cluster. You can use `return_major_cluster` to get the
  major cluster number.
- `--filter_applied` argument is a flag that indicates whether the variable filter has been
  applied to select good scoring models. If this flag is set, the script will use the
  variable filter output directory to extract the selected models. If this flag is not set,
  the script will extract all models from the specified cluster.

#### 4. Assess sampling exhaustiveness using sampcon

```bash

python /path/to/imp-clean/build/lib/IMP/sampcon/exhaust.py \\
  --path /path/to/pmi_analysis_output \\
  --sysname my_system \\
  --scoreA "A_models_clust1.txt" \\
  --scoreB "B_models_clust1.txt" \\
  --rmfA "A_models_clust1.rmf3" \\
  --rmfB "B_models_clust1.rmf3" \\
  --density /path/to/density.txt \\
  --voxel 5.0 \\
  --gridsize "5" \\
  --matrix-cores 12 \\
  --cluster-cores 4 \\
  --mode cpu_omp \\
  --gnuplot \\
  --prism \\
  --align

```

- `--path` argument specifies the path to the directory containing the PMI analysis output.
- `--sysname` argument specifies the user-defined name of the system being analyzed.
- `--scoreA` and `--scoreB` arguments specify the score files for the two sets of models
  to be compared. These are obtained from the `run_analysis_trajectories.py` script and
  contain the scores of the models in each cluster.
- `--rmfA` and `--rmfB` arguments specify the RMF files for the two sets of models to be
  compared. These are obtained from the `run_extract_models.py` script and contain the
  coordinates of the selected models in each cluster.
- `--density` argument specifies the path to the density file for the system. This file
  defines the segregation of the system into different regions for localization probability
  density calculation.
- `--voxel` argument specifies the voxel size for the density calculation. This value
  should be chosen based on the resolution of the density map and the size of the system.
- `--gridsize` argument specifies the grid size for the density calculation. This value
  should be chosen based on the size of the system and the desired resolution of the
  density map.
- `--matrix-cores` argument specifies the number of cores to use for matrix calculations.
- `--cluster-cores` argument specifies the number of cores to use for clustering calculations.
- `--mode` argument specifies the mode of operation for the sampcon analysis. The default
  mode is `cpu_omp`, which uses OpenMP for parallel processing on the CPU.
- `--gnuplot` argument is a flag that indicates whether to generate gnuplot scripts for
  visualizing the results. If this flag is set, gnuplot scripts will be generated
  for visualizing the results. If this flag is not set, gnuplot scripts will not be generated.
- `--prism` argument is a flag that indicates whether to generate input for PrISM.
- `--align` argument is a flag that indicates whether to align the models before calculating
  the localization probability density.

#### 5. Correlate the localization probability density maps from samples A & B

```bash

python correlate_cluster_sample_densities.py \\
  --sampcon_cluster_path /path/to/sampcon_output/cluster.0 \\
  --mode cpu_omp \\
  --use_combined_map

```

- `--sampcon_cluster_path` argument specifies the path to the directory containing the
  sampcon output for the cluster being analyzed. This directory should contain the
  localization probability density maps for the two sets of models being compared.

- `--mode` argument specifies the mode of operation for the correlation analysis. The default
  mode is `cpu_omp`, which uses OpenMP for parallel processing on the CPU.

- `--use_combined_map` argument is a flag that indicates whether to use the combined
  localization probability density map for the correlation analysis. If this flag is set,
  the combined map will be used. If this flag is not set, the individual maps for
  each region specfied in the density file will be used for the correlation analysis.

#### 6. Align rigid body PDBs to the cluster center model

```bash

python align_pdb_to_ccm.py \\
  --ccm_file /path/to/cluster_center_model.rmf3 \\
  --input /path/to/input_pdbs \\
  --output /path/to/aligned_pdbs

```

- `--ccm_file` argument specifies the path to the cluster center model RMF file. This file
  contains the coordinates of the cluster center model to which the input PDBs will be aligned.

- `--input` argument specifies the path to the directory containing the input PDB files to
  be aligned to the cluster center model.

- `--output` argument specifies the path to the directory where the aligned PDB files will
  be saved.

#### 7. Extract the models from a sampcon cluster into a single RMF file

```bash

python extract_sampcon.py \\
  --rmf_out /path/to/sampcon_extracted_frames.rmf3 \\
  --rmf1 "A_models_clust1.rmf3" \\
  --rmf2 "B_models_clust1.rmf3" \\
  --list1 "cluster.0.sample_A.txt" \\
  --list2 "cluster.0.sample_B.txt"

```

- `--rmf_out` argument specifies the path to the output RMF file that will contain the
  extracted models from the sampcon cluster.

- `--rmf1` and `--rmf2` arguments specify the RMF files for the two sets of models to be
  extracted. These are obtained from the `run_extract_models.py` script and contain the
  coordinates of the selected models in each cluster.

- `--list1` and `--list2` arguments specify the text files containing the list of frame
  numbers to be extracted from the RMF files. These files are generated by the sampcon
  analysis and contain the frame numbers of the models in each sampcon cluster.

#### 8. PrISM analysis

```bash

- Perform PrISM analysis on the extracted models to assess the precision of
  different regions.

python /path/to/prism/src/main.py \\
  --input /path/to/prism_input.npz \\
  --input_type npz \\
  --voxel_size 5.0 \\
  --output /path/to/prism_output \\
  --classes 2 \\
  --cores 12 \\
  --models 1 \\
  --n_breaks 50 \\
  --resolution 1

```

- `--input` argument specifies the path to the input file for PrISM analysis. This file
  should be in NPZ format and contain the coordinates of the extracted models. You can
  obtain this file from the output of `exhaust.py` if you set the `--prism` flag.

- `--input_type` argument specifies the type of input file. The default is `npz`, which
  indicates that the input file is in NPZ format.

- `--voxel_size` argument specifies the voxel size for the PrISM analysis. This value
  should be chosen based on the resolution of the density map and the size of the system.

- `--output` argument specifies the path to the directory where the PrISM output will be
  saved.

- `--classes` argument specifies the number of classes for the PrISM analysis. The default
  is 2, which will divide the precision levels into five categories.

- `--cores` argument specifies the number of cores to use for parallel processing during
  the PrISM analysis.

- `--models` argument specifies the fraction of models to use for the PrISM analysis. The
  default is 1, which will use all models in the input file.

- `--n_breaks` argument specifies the number of breaks for jenkspy.

- `--resolution` argument specifies the resolution as the number of residues per bead.
  This is used to specify the resolution at which the precision annotation is generated.

<hr>

- Color the cluster center model based on the PrISM annotations.

```bash

python /path/to/prism/src/color_precision.py \\
  --input /path/to/cluster_center_model.rmf3 \\
  --frame_index 0 \\
  --resolution 1 \\
  --annotations_file /path/to/prism_output/annotations.txt \\
  --output /path/to/cluster_center_model_colored.rmf3

```

- `--input` argument specifies the path to the cluster center model RMF file. This file
  contains the coordinates of the cluster center model to which the PrISM annotations
  will be applied.

- `--frame_index` argument specifies the frame index of the cluster center model to be
  colored based on the PrISM annotations. The default is 0, which indicates the first
  frame of the RMF file.

- `--resolution` argument specifies the resolution as the number of residues per bead.
  This is used to specify the resolution at which the precision annotation is generated.

- `--annotations_file` argument specifies the path to the PrISM annotations file. This
  file is generated by the PrISM analysis and contains the precision annotations for
  each bead in the integrative structure.

#### 9. Obtain XYZR coordinates of the beads from the extracted models

```bash

python rmf_to_xyzr.py \\
  --rmf_path /path/to/sampcon_extracted_frames.rmf3 \\
  --output_path /path/to/xyzr_output.hdf5 \\
  --float_dtype 32 \\
  --nproc 8

```

- `--rmf_path` argument specifies the path to the RMF file containing the extracted models
  from the sampcon cluster. This file is generated by the `extract_sampcon.py` script and
  contains the coordinates of the selected models in each cluster.

- `--output_path` argument specifies the path to the output HDF5 file that will contain
  the XYZR coordinates of the beads from the extracted models.

- `--float_dtype` argument specifies the floating point data type to use for storing the
  XYZR coordinates in the output HDF5 file. The default is 32, which indicates that the
  coordinates will be stored as 32-bit floating point numbers.

- `--nproc` argument specifies the number of cores to use for parallel processing during
  the extraction of XYZR coordinates from the RMF file.

#### 10. Obtain pairwise contact maps for all modeled molecules in the system

```bash

python interaction/coarse_grained/interaction_map.py \\
  --xyzr_file /path/to/xyzr_output.hdf5 \\
  --nproc 8 \\
  --contact_cutoff 8.0 \\
  --fraction_cutoff 0.25 \\
  --interaction_map_dir /path/to/interaction_map_output \\
  --plotting matplotlib \\
  --float_dtype 32 \\
  --int_dtype 32

```

- `--xyzr_file` argument specifies the path to the HDF5 file containing the XYZR coordinates
  of the beads from the extracted models. This file is generated by the `rmf_to_xyzr.py`.

- `--nproc` argument specifies the number of cores to use for parallel processing during
  the generation of pairwise contact maps.

- `--contact_cutoff` argument specifies the distance cutoff (in Angstroms) for defining
  contacts between beads. Beads that are within this distance of each other will be
  considered to be in contact.

- `--fraction_cutoff` argument specifies the fraction of models in which a contact must
  be present for it to be included in the final contact map. For example, a value
  of 0.25 means that a contact must be present in at least 25% of the models to be
  included in the final contact map.

- `--interaction_map_dir` argument specifies the path to the directory where the
  generated pairwise contact maps will be saved.

- `--plotting` argument specifies the plotting library to use for generating visualizations
  of the contact maps. The default is `matplotlib`, which uses the Matplotlib library
  for plotting. You can also specify `plotly` to use the Plotly library for interactive
  visualizations.

- `--float_dtype` argument specifies the floating point data type to use for storing the
  contact maps in the output files.

- `--int_dtype` argument specifies the integer data type to use for storing the contact
  maps in the output files.

"""
